@startuml
title Ubuntu Pro Magic Attach Process

participant User
participant "Ubuntu Init" as Installer
participant "Provd (Backend)" as Provd
participant "Pro API" as ProAPI
participant "ubuntu.com/pro" as Server

Installer->Provd: AttachUbuntuPro (gRPC stream)
Provd->ProAPI: pro initiate
ProAPI->Server: pro initiate
Server-->ProAPI: user code
ProAPI-->Provd: user code
Provd-->Installer: user code (stream)
Installer-->User: user code

Provd->ProAPI: pro wait
ProAPI->Server: pro wait
loop Polling
    Server-->ProAPI: waiting for user code
end
User->Server: Input user code
Server-->ProAPI: contract token
ProAPI-->Provd: contract token
Provd->ProAPI: pro attach with contract token
ProAPI->Server: pro attach with contract token
Server-->ProAPI: machine attached to Pro
ProAPI-->Provd: machine attached to Pro
Provd-->Installer: success (stream)
Installer-->User: success dialog
@enduml